version: '3.9'
services:

  nginx:
    image: nginx:1.23.3
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - api/.env
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./volumes/nginx/logs:/var/log/nginx:delegated
    networks:
      - internal
    depends_on:
      - api
      - client

  db:
    image: postgres:15.2-alpine3.17
    ports:
      - "5432"
    expose:
      - "5432"
    env_file:
      - ./api/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    env_file:
      - api/.env
    build:
      context: ./api
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    networks:
      - internal

  client:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata:

