version: '3.9'
services:

  nginx:
    image: nginx:1.23.3
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - api/.env
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./volumes/nginx/logs:/var/log/nginx:delegated
    networks:
      - api-layer
      - web-layer
    depends_on:
      - api
      - web

  db:
    image: postgres:15.2-alpine3.17
    ports:
      - "5432"
    env_file:
      - ./api/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db-layer
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    env_file:
      - api/.env
    build:
      context: ./api
    ports:
      - "8000"
    depends_on:
      - db
    networks:
      - api-layer
      - db-layer

  web:
    build:
      context: ./web
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - web-layer

networks:
  db-layer:
  api-layer:
  web-layer:

volumes:
  pgdata:

