version: '3.9'

services:
  nginx:
    image: nginx:1.23.3
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - api/.env
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./volumes/nginx/logs:/var/log/nginx:delegated
    networks:
      - api-layer
      - web-layer
      - s3-layer
    depends_on:
      - api
      - web
      - s3

  db:
    image: postgres:15.2-alpine3.17
    ports:
      - "5432"
    env_file:
      - ./api/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db-layer
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated

  api:
    env_file:
      - api/.env
    build:
      context: ./api
    ports:
      - "8000"
    depends_on:
      - db
    networks:
      - api-layer
      - db-layer
      - s3-layer

  web:
    build:
      context: ./web
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - web-layer

  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - s3
    env_file:
      - ./api/.env
    volumes:
      - ./services/mc:/tmp/seeds:ro
    entrypoint: /tmp/seeds/entrypoint.sh
    networks:
      - s3-layer

  s3:
    image: quay.io/minio/minio:latest
    command: server /data
    ports:
      - "9000"
    env_file:
      - ./api/.env
    volumes:
      - ./volumes/s3:/data:delegated
    networks:
      - s3-layer
      - api-layer

networks:
  db-layer:
  api-layer:
  web-layer:
  s3-layer:
