version: '3.9'

services:
  nginx:
    image: nginx:1.24.0
    ports:
      - "127.0.0.1:${REVERSE_PROXY_PORT}:80"
    env_file:
      - api/.env
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./volumes/nginx/logs:/var/log/nginx:delegated
    networks:
      - api-layer
      - web-layer
      - s3-layer
    depends_on:
      - api
      - web
      - s3

  db:
    image: postgres:15.3
    ports:
      - "127.0.0.1:${DATABASE_PORT}:${POSTGRES_PORT}"
    env_file:
      - ./api/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db-layer
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated

  api:
    env_file:
      - ./api/.env
    environment:
      - MINIO_HOST=s3:9000
    build:
      context: ./api
    ports:
      - "127.0.0.1:${API_PORT}:8000"
    depends_on:
      - db
    networks:
      - api-layer
      - db-layer
      - s3-layer

  memcached:
   image: memcached:1.6
   ports:
     - "127.0.0.1:${CACHE_PORT}:11211"
   entrypoint:
    - memcached
    - -m 64
   networks:
    - api-layer
   depends_on:
     - api

  web:
    build:
      context: ./web
    ports:
      - "127.0.0.1:${FRONT_PORT}:3000"
    environment:
      - VITE_REACT_APP_NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./web/.env
    depends_on:
      - api
    networks:
      - web-layer

  s3:
    image: quay.io/minio/minio:RELEASE.2023-06-29T05-12-28Z
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:${S3_PORT}:9000"
      - "127.0.0.1:${S3_CONSOLE_PORT}:9001"
    env_file:
      - ./api/.env
    volumes:
      - ./volumes/s3:/data:delegated
    networks:
      - s3-layer
      - api-layer

networks:
  db-layer:
  api-layer:
  web-layer:
  s3-layer: