version: '3.9'

services:
  db:
    image: postgres:15.3
    ports:
      - "127.0.0.1:5431:5432"
    env_file:
      - ./api/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated
    network_mode: host

  api:
    env_file:
      - ./api/.env
    build:
      context: ./api
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    network_mode: host

  memcached:
   image: memcached:1.6
   ports:
     - "127.0.0.1:11211:11211"
   entrypoint:
    - memcached
    - -m 64
   depends_on:
     - api
   network_mode: host

  web:
    build:
      context: ./web
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - VITE_REACT_APP_NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./web/.env
    depends_on:
      - api
    network_mode: host

  s3:
    image: quay.io/minio/minio:RELEASE.2023-06-29T05-12-28Z
    command: server --console-address ":9001" --address ":9000" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    env_file:
      - ./api/.env
    volumes:
      - ./volumes/s3:/data:delegated
    network_mode: host

