# Generated by Django 4.1.7 on 2023-04-12 09:54

import api.models.utils
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_created=True, editable=False)),
                ('ips', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), size=None)),
                ('ports', django.contrib.postgres.fields.ArrayField(base_field=api.models.utils.NmapPortField(), size=None)),
                ('recon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recon')),
            ],
            options={
                'verbose_name': 'Nmap data',
                'verbose_name_plural': 'Nmap data',
                'ordering': ['id'],
            },
        ),
    ]
