# Generated by Django 4.1.7 on 2023-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulntype',
            name='id',
        ),
        migrations.AlterField(
            model_name='auth',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pentester'), (2, 'manager')], editable=False),
        ),
        migrations.AlterField(
            model_name='vulntype',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
