# Generated by Django 4.2 on 2023-05-06 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='scope',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), max_length=64, size=None),
        ),
    ]
