# Generated by Django 4.1.7 on 2023-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vulnerability TYPE Model',
                'verbose_name_plural': 'Vulnerability TYPES models',
                'ordering': ['name'],
            },
        ),
    ]
