# Generated by Django 4.1.7 on 2023-02-26 12:35

from django.db import migrations

def add_vulnerability_types(apps, schema_editor):
    """
        Source: CVE.
    """
    VulnType = apps.get_model('api', 'VulnType')
    db_alias = schema_editor.connection.alias
    VulnType.objects.using(db_alias).bulk_create([
        VulnType(name="DoS"),
        VulnType(name="Code execution"),
        VulnType(name="Overflow"),
        VulnType(name="Memory Corruption"),
        VulnType(name="SQL Injection"),
        VulnType(name="XSS"),
        VulnType(name="Directory Traversal"),
        VulnType(name="Http Response Splitting"),
        VulnType(name="Bypass Something"),
        VulnType(name="Gain Information"),
        VulnType(name="Gain Privileges"),
        VulnType(name="CSRF"),
        VulnType(name="File Inclusion"),
    ])
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagemodel_vulntype_alter_pentester_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_vulnerability_types)
    ]
