# Generated by Django 4.2 on 2023-04-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vulnerability_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='is_disabled',
            new_name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='tmp_token',
        ),
    ]
