# Generated by Django 4.2 on 2023-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_disabled_auth_is_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.TextField(default='New note'),
        ),
    ]
