# Generated by Django 4.2 on 2023-05-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_serverity_vulnerability_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crtsh',
            name='recon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crtsh_runs', to='api.recon'),
        ),
        migrations.AlterField(
            model_name='nmapscan',
            name='recon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nmap_runs', to='api.recon'),
        ),
    ]
