# Generated by Django 4.1.7 on 2023-03-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_builtin_vuln_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('members', models.ManyToManyField(blank=True, to='api.pentester')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
    ]
