# Generated by Django 4.1.7 on 2023-03-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Manager',
        ),
    ]
