# Generated by Django 4.2 on 2023-05-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mission_scope'),
        ('api', '0005_alter_vulnerability_images'),
    ]

    operations = [
    ]
