# Generated by Django 4.1.7 on 2024-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessage_sender_chatmessage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
