# Generated by Django 4.1.7 on 2024-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatmessage_sender_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthtml',
            name='pdf_file',
            field=models.CharField(max_length=512, blank=True, null=True),
        ),
    ]
