# Generated by Django 4.2 on 2023-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_crtsh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
