# Generated by Django 4.2.1 on 2023-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20230510_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
