# Generated by Django 4.1.7 on 2024-02-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240228_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthtml',
            name='updated_at',
        ),
    ]
