# Generated by Django 4.2.3 on 2023-07-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_vulnerability_options_auth_favorites_and_more'),
        ('api', '0009_alter_vulnerability_options_clientinfo'),
    ]

    operations = [
    ]
