# Generated by Django 4.1.7 on 2023-03-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_notes_author_alter_vulnerability_author_squashed_0009_alter_vulnerability_vuln_type'),
        ('api', '0005_rename_admin_manager'),
    ]

    operations = [
    ]
