# Generated by Django 4.2.3 on 2023-07-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_auth_favorites_auth_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='profile_image',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
