# Generated by Django 4.2 on 2023-09-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auth_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('css_style', models.TextField()),
                ('cover_html', models.TextField()),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
            },
        ),
        migrations.CreateModel(
            name='ReportHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=1.0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_id', to='api.mission')),
                ('template', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='template_id', to='api.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Html',
                'verbose_name_plural': 'Reports Html',
            },
        ),
    ]
