# Generated by Django 4.2.3 on 2023-09-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapscan',
            name='nmap_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='os_details',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='scan_date',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
