# Generated by Django 4.2.3 on 2023-09-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_credentials'),
        ('api', '0014_alter_auth_profile_image_alter_vulnerability_images'),
    ]

    operations = [
    ]
