# Generated by Django 4.2.3 on 2023-09-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_mission_scope'),
        ('api', '0015_merge_20230911_1909'),
    ]

    operations = [
    ]
