# Generated by Django 4.2.3 on 2023-09-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reporttemplate_reporthtml'),
        ('api', '0016_merge_20230915_1356'),
    ]

    operations = [
    ]
