# Generated by Django 4.2.3 on 2023-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_credentials_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='mission',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
