# Generated by Django 4.2.3 on 2023-10-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_mission_options_reporthtml_html_file_and_more'),
        ('api', '0020_alter_credentials_mission'),
    ]

    operations = [
    ]
