# Generated by Django 4.2.3 on 2023-10-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_auth_first_name_alter_auth_last_name'),
        ('api', '0021_merge_20231011_1454'),
    ]

    operations = [
    ]
