# Generated by Django 4.2.3 on 2023-10-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20231012_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
