# Generated by Django 4.2.3 on 2023-11-13 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_mission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='freelance_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auth',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pentester'), (2, 'manager'), (3, 'freelancer')], editable=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer',
                'verbose_name_plural': 'Freelancers',
                'ordering': ['creation_date'],
            },
        ),
    ]
