# Generated by Django 4.1.7 on 2023-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_mission_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Mailing List Item',
                'verbose_name_plural': 'Mailing List Items',
            },
        ),
    ]
