# Generated by Django 4.2.3 on 2023-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_mission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='logo',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
    ]
