# Generated by Django 4.2.3 on 2023-11-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mission_freelance_member_alter_auth_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_of', to='api.team'),
        ),
    ]
