# Generated by Django 4.2.3 on 2023-11-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_mission_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creds', to='api.mission'),
        ),
    ]
