# Generated by Django 4.2.3 on 2023-11-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mission_logo'),
        ('api', '0026_alter_credentials_mission'),
    ]

    operations = [
    ]
