# Generated by Django 4.1.7 on 2023-12-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mailinglistitem'),
        ('api', '0027_merge_20231116_1548'),
    ]

    operations = [
    ]
