# Generated by Django 4.2.3 on 2023-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20231116_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='has_otp',
            field=models.BooleanField(default=False),
        ),
    ]
