# Generated by Django 4.2.3 on 2023-12-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_reporthtml_pdf_file'),
        ('api', '0027_merge_20231116_1548'),
    ]

    operations = [
    ]
