# Generated by Django 4.2.3 on 2023-12-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20231206_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthtml',
            name='logo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reporthtml',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
