# Generated by Django 4.2.3 on 2023-12-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_reporthtml_logo_alter_reporthtml_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthtml',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
