# Generated by Django 4.2.7 on 2023-12-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_0024_mailinglistitem_0027_merge_20231116_1548'),
        ('api', '0029_auth_mfa_secret'),
    ]

    operations = [
    ]
