# Generated by Django 4.2.7 on 2024-01-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20231230_1601'),
        ('api', '0030_merge_20240105_1154'),
    ]

    operations = [
    ]
