# Generated by Django 4.2.3 on 2024-01-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20240105_1154'),
        ('api', '0030_reporthtml_updated_at'),
    ]

    operations = [
    ]
