# Generated by Django 4.2.7 on 2024-01-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20240106_1553'),
        ('api', '0031_merge_20240110_1737'),
    ]

    operations = [
    ]
