name: frontend-lint
on: [push, pull_request]

jobs:
  build:
    name: Lint the frontend
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '(web)')
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: 'web' # will run `yarn test` in `frontend` sub folder
      - name: Lints the app
        uses: borales/actions-yarn@v4
        with:
          cmd: lint # will run `yarn test` command
          dir: 'web' # will run `yarn test` in `frontend` sub folder
