name: CI
on: [push]

jobs:
  build:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: 'web' # will run `yarn test` in `frontend` sub folder
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command
          dir: 'web' # will run `yarn test` in `frontend` sub folder
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit # will run `yarn test` command
          dir: 'web' # will run `yarn test` in `frontend` sub folder
      - name: Run coverage
        uses: borales/actions-yarn@v4
        with:
          cmd: test:coverage
          dir: 'web' # will run `yarn test` in `frontend` sub folder